version: '3.5'

services:
    icos-shell-backend:
        image: michalkeit/icos-shell-backend
        build: ./
        container_name: icos-shell-backend
        restart: always
        ports:
            - "8080:8080"
        volumes:
            - ./config_server.yml:/app/config.yml
    lighthouse:
        image: michalkeit/icos-shell-backend
        container_name: lighthouse
        ports:
            - "8081:8080"
        volumes:
            - ./config_lighthouse.yml:/app/config.yml

        
